using System.Text.Json;
using System.Text.Json.Nodes;

namespace CU_ReproRunner.Schema;

/// <summary>
/// Wraps a customer-provided fieldSchema JSON into a full CU analyzer definition,
/// pinning the completion + embedding model deployments for residency-safe routing.
/// Never mutates the source file — operates on a parsed JsonNode clone.
/// </summary>
public static class SchemaWrapper
{
    public static string Wrap(
        string sourceSchemaJson,
        string analyzerId,
        string completionModel,
        string embeddingModel,
        string baseAnalyzerId = "prebuilt-document",
        string? description = null)
    {
        if (string.IsNullOrWhiteSpace(sourceSchemaJson))
            throw new ArgumentException("Source schema JSON is empty.", nameof(sourceSchemaJson));

        var sourceNode = JsonNode.Parse(sourceSchemaJson)
            ?? throw new InvalidOperationException("Source schema is not valid JSON.");

        if (sourceNode is not JsonObject sourceObj)
            throw new InvalidOperationException("Source schema root must be a JSON object.");

        // Pull the fieldSchema sub-tree (deep clone to avoid mutating source).
        if (!sourceObj.TryGetPropertyValue("fieldSchema", out var fieldSchemaNode) || fieldSchemaNode is null)
            throw new InvalidOperationException("Source schema must contain a top-level 'fieldSchema' property.");

        var fieldSchemaClone = JsonNode.Parse(fieldSchemaNode.ToJsonString())!;

        var wrapped = new JsonObject
        {
            ["analyzerId"] = analyzerId,
            ["baseAnalyzerId"] = baseAnalyzerId,
            ["description"] = description
                ?? "FCT Canada title-search multiline repro analyzer (auto-generated by CU_ReproRunner)",
            ["models"] = new JsonObject
            {
                ["completion"] = completionModel,
                ["embedding"] = embeddingModel,
            },
            ["fieldSchema"] = fieldSchemaClone,
        };

        return wrapped.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
    }
}
